server:
  port: 8090


spring:
  mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
  thymeleaf:
    cache: false
    prefix: classpath:/WEB-INF/jsp/
    suffix: .jsp
  datasource:
        name: test
        url: ENC(KaXsX1rgkRTdjeuSDC9chDXNnRIGAERJo8IKojTNZpvtwN/KD2u+5g6Fxgxujd18SW9eX796jsuUJoCRbn5r2v0LArlyPK8pCqQ1nl3fJqCBZ9eOrUxI1D2ZnuvQ+FRn4KJtuPmEOsw=)
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
  mybatis:
     type-aliases-package: springboot.bootdemo.generratorpojo  # 注意：对应实体类的路径
     mapper-locations: classpath*:**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  mail:
    host: smtp.126.com
    username: 111
    password: 111
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#Redis
  redis:
      database: 0
      host: 12.3.10.160
      password: ''
      port: 6379

#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
#密钥
jasypt:
  encryptor:
    password: www
